### ISSUE TITLE
How to run sas code via the extension?

### ISSUE THREAD

**Issue by sniperhgy** [VaccineAndDrugEvaluationCentre/vscode-sas-language#1]
Dear Developer,

I have installed SAS 9.3 on my pc, and how can I run the sas code via your extension in vs code? Please teach me. Thank you very much.

Best Regards,

Sniperhgy

**Comment by Righolt** [comment]
Hi Sniperhgy,

The extension is currently only set up as an editor, not to run SAS from within VS code.

**Comment by sniperhgy** [comment]
Sure, got it, thank you very much.
