### ISSUE TITLE
Asterisk (*) in a proc sql

### ISSUE THREAD

**Issue by skynetforcats** [VaccineAndDrugEvaluationCentre/vscode-sas-language#2]
Asterisk (*) in a proc sql is interpreted as comment begin.

**Comment by Righolt** [comment]
@ACrazyConcept Do you have an example of this, as I though that some of the instances we checked before dealt with this appropriately.

**Comment by skynetforcats** [comment]
An example:


Proc sql;
Connect to oracle
(path="" user="" password="" DBMAX_TEXT=32767 PRESERVE_COMMENTS);
Create table t1 as
Select
*
From connection to oracle
(
select distinct
t1.f1
,t1.f2


Proc sql;
Connect to oracle
(path="" user="" password="" DBMAX_TEXT=32767 PRESERVE_COMMENTS);
Create table t1 as
Select
f1
,f2
From connection to oracle
(
select distinct
t1.f1
,t1.f2

**Comment by Righolt** [comment]
@ACrazyConcept Thanks for the example, I see the issue, it seems to appear when the `*` is the start of the line. When using `Select *` without a line break it does not cause an issue. 

I will see whether there is way to resolve this while still interpreting actual in-line comment properly.

**Comment by Righolt** [comment]
@ACrazyConcept I have not been able as of yet to find a solution for this unfortunately.

**Comment by gloc-mike** [comment]
How about auto-format code snippets like this? If you do that then lone-wolf asterisks will be rightly placed along side the 'select' statement rather than on a separate line. Lets face it, the format of the example above is terrible. If it were re-formatted by the editor into a more readable, human friendly format then you won't have the problem any longer. 
✨😄✨

**Comment by Righolt** [comment]
That is an interesting idea. @ACrazyConcept would that be a reasonable workaround for your coding style?

**Comment by skynetforcats** [comment]
Thanks for looking into it! I can absolutely live with the workaround to keep select and * to the same line :)
