### ISSUE TITLE
Executing the SAS code in VS Code

### ISSUE THREAD

**Issue by TCEagleInSV** [VaccineAndDrugEvaluationCentre/vscode-sas-language#3]
How about writing some simple code to execute SAS using A Run Task in your extension.  For example, as a task I wrote the following:
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run SAS",
            "type": "process",
            "windows": {
                "command": "C:\\Program Files\\SASHome\\SASFoundation\\9.4\\sas.exe",
                "args": ["${file}"]
            }
        }
    ]
}

This executes SAS on the current file in the editor in the working directory.  The drawback of tasks are they are workplace dependent.  I have to copy the .vscode directory into every directory I am working in...  I don't know how to write an extension yet...

Tom Eagle

**Comment by Righolt** [comment]
Interesting idea, if you end up incorporating this in the extension, it would be very valuable to include it.

**Comment by TCEagleInSV** [comment]
That's where I am a little lost.  Is it possible to edit your json files and they still work?  Which json should I put this code into?

Thank you

Tom Eagle

On May 24, 2018, at 7:31 AM, Righolt <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting idea, if you end up incorporating this in the extension, it would be very valuable to include it.

**Comment by Righolt** [comment]
You will probably need to work in a branch/fork and load that version in your local VS code to see what works. I never implemented the idea you have, so I do not know what the recommendation would be. The link you provide seems to indicate you would need to create a tasks.json, but it might be good looking at some other language implementations for ideas.

**Comment by TCEagleInSV** [comment]
Thanks, I will look at that.  I will keep you informed of my progress.

Tom

**Comment by Righolt** [comment]
Closing this now, open a pull request when needed.

**Comment by Tgillett84** [comment]
Did it work? I'm going issues running my sas with Python so I was trying to see if vs code would work

**Comment by TCEagleInSV** [comment]
Yes I use SAS with VScode and use the Vaccine and Drug Control Centre’s VS Code SAS coding extension.  However, I had to add a .vscode set of commands to execute SAS directly from within VSCode.  I’d be glad to share that with you.

Tom

On Mar 30, 2022, at 6:05 AM, Tameka Gillett ***@***.***> wrote:

﻿

Did it work? I'm going issues running my sas with Python so I was trying to see if vs code would work

**Comment by Tgillett84** [comment]
Yes please can you share because I keep getting errors on my side.

Thank you,

Tameka Gillett, MBA

**Comment by TCEagleInSV** [comment]
You will have to adjust the directory information. Unzip the file and then add the attached subdirectory with its JSON file in any directory where you wish to edit and run SAS code.  Then in VS Code itself add a keystroke shortcut for alt + key (I use Alt + R) to select Run Task “Run SAS” (Equivalent to Ctrl-Shift-P and then selecting Run SAS).

Tom

**Comment by Tgillett84** [comment]
Awesome. Thank you so much!

Thank you,

Tameka Gillett, MBA
