### ISSUE TITLE
Better comments plug-in not working when using this plug-in

### ISSUE THREAD

**Issue by xiaosongz** [VaccineAndDrugEvaluationCentre/vscode-sas-language#4]
Hello, 

Thanks a lot for developing syntax highlighter for SAS, it's extremely helpful!
Your plugin is so far the best on the VSCODE marketplace, but it seems it's blocking the syntax highlighting for the "Better Comments" plugin. I wonder if there is a way that we can allow the "better comments" plugin to change the text color for the text in comments section?

Thank you!

**Comment by Righolt** [comment]
I'm not sure what exactly is blocking it. Have you cross-posted this on the Better Comments repo?

**Comment by xiaosongz** [comment]
I didn't yet post on their repo, but I did test the other SAS grammar plugin like [THIS ONE](https://marketplace.visualstudio.com/items?itemName=77qingliu.sas-syntax) and it seems working fine with the **Better Comments** plugin. 
I guest there are some coloring logics in your code that have a much higher priority than theirs? Or their plugin didn't detect the comments as "comments" that need to highlight?

This is just my uneducated guess, I am sorry that I do not have enough technique ability to provide more useful info in the "Syntax-highlighting" world.

**Comment by Righolt** [comment]
I'm not quite sure how VS Code handles priorities, if there is an easy fix I would be happy to implement it, but the creator of Better Comments may have a better idea of how to handle this.

**Comment by xiaosongz** [comment]
I just looked in their repo and it seems that their parser for SAS is quite simple
[Here](https://github.com/aaron-bond/better-comments/search?q=sas) is all the pieces related to _SAS_ in their repo. And I believe they detect comments by the following code:
https://github.com/aaron-bond/better-comments/blob/b0ede0b0fa9cd87afb2aca9fbb04136d57537688/src/parser.ts#L379-L382

I this it is the same logic you used in 
https://github.com/VaccineAndDrugEvaluationCentre/vscode-sas-language/blob/ae8e15a1f32cb9267142de1c1f665ce4f4b8ec27/language-configuration.json#L2-L6

**Comment by xiaosongz** [comment]
I think it might be even simpler than I thought!

https://github.com/77QingLiu/vscode-SAS.tmLanguage/blob/9dc00fecb3835f8ff38f5eb35dfc14f2bdef6875/syntaxes/sas.tmLanguage.json#L3

Could it be this? Since it's called "SAS Language" instead of "SAS" or "sas' so their **parser.ts** didn't even try do anything since it's not in the list?

https://github.com/VaccineAndDrugEvaluationCentre/vscode-sas-language/blob/ae8e15a1f32cb9267142de1c1f665ce4f4b8ec27/syntaxes/sas.tmLanguage#L13-L14

**Comment by Righolt** [comment]
I changed it in here (but not as an release), can you give this a try and see whether it works as intended. If it does, I will create a release, otherwise, I'll revert.

Thanks.

**Comment by Righolt** [comment]
Thanks @xiaosongz ; I reverted my prior changes and just pushed a new release based on you pull request. Can you confirm it works as intended?

**Comment by xiaosongz** [comment]
> Thanks @xiaosongz ; I reverted my prior changes and just pushed a new release based on you pull request. Can you confirm it works as intended?

I just installed it as .vsix and it works. 

Just remember to **also change** the version to `0.1.3` in your `package.json` file

**Comment by xiaosongz** [comment]
Hi @Righolt, I saw you released the `0.1.3` on GitHub. Is there something else we need to do to make it available on the marketplace?

**Comment by Righolt** [comment]
Just forgot the username and trying to get back into the account.

**Comment by Righolt** [comment]
@xiaosongz It took a while, but I finally got access to the account and published the update.
