### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by madhavajay** [VaccineAndDrugEvaluationCentre/vscode-sas-language#6]
Is there any chance there is a formatter for SAS in VSCode? 🤓

**Comment by Righolt** [comment]
@madhavajay We haven't anything to this extension.

**Comment by madhavajay** [comment]
@Righolt how hard do you think it would be to add? Are there any well documented style guides for SAS that you are aware of which could be used to implement a VSCode formatter?

**Comment by Righolt** [comment]
People use different styles, but I think adding snippets setting up common steps like a data steps, proc freq, proc sql etc. would help as well. If you look more for a linter, I think indentation, uniform case, etc would be good things to start with.
